# Server Port
server.port=8080

# MongoDB Configuration
# Replace with your local MongoDB URI or Atlas URI
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.resourceapp=DEBUG

# Validation
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
