# Server Configuration
server.port=8081

# MongoDB Atlas Configuration
spring.data.mongodb.uri=${MONGODB_URI}

# Jackson Configuration for LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
